### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by SalvatoreAD** [IhorKlimov/SmartImagePicker#10]
when I call imagePicker.choosePicture(true); I have this error:

> java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/*********/files/images/outputImage1529499833245.jpg
> at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
>         at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
>         at com.myhexaville.smartimagepicker.ImagePicker.getCameraIntent(ImagePicker.java:259)
>         at com.myhexaville.smartimagepicker.ImagePicker.startImagePickerActivity(ImagePicker.java:288)
>         at com.myhexaville.smartimagepicker.ImagePicker.choosePicture(ImagePicker.java:85)

**Comment by Ibrahimhassan1** [comment]
@SalvatoreAD 
I had the same issue and adding this line to my `file_paths.xml` fixes the crash:
`<files-path name="img" path="images/" />`
This is from my AndroidManifest.xml:
```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.domain.appname.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
```
