### ISSUE TITLE
READ Permissions and also no way to proceed from Crop?

### ISSUE THREAD

**Issue by shahzadyounas** [IhorKlimov/SmartImagePicker#4]
When trying to select image, Android first asks for permissions (write?) and I accept. But then I can not select an image:

11-13 14:24:16.265 4183-5697/? E/DatabaseUtils: Writing exception to parcel
                                                java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=4092, uid=10050 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                    at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:608)
                                                    at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:483)
                                                    at android.content.ContentProvider$Transport.query(ContentProvider.java:212)
                                                    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                    at android.os.Binder.execTransact(Binder.java:565)

Also - using the crop built in, shows the image and crop but there is no way to proceed/save once resized in the cropper?

**Comment by bhavna-nga** [comment]
I'm having the same issue !!
Have you got any solution for the same ?

**Comment by HosseinKurd** [comment]
I have the same issue too!

**Comment by ivorywebdesign** [comment]
Remove any provider if u have set .
I am unable to find crop toolbar .I have set theme to default theme still cant find any toolbar to proceed cropping
